#!/bin/sh
#
# Vendors INSLIB and its KFCore submodule into this example, then generates the
# per-translation-unit wrappers that carry the build configuration.
#
# Run it once from anywhere:
#
#     ./fetch_inslib.sh
#
# Afterwards the sketch compiles like any other Arduino sketch. Nothing it
# writes is tracked by git (see .gitignore) - re-run it to update.
#
# ---------------------------------------------------------------------------
# LICENSING - read this before you ship anything built with it
# ---------------------------------------------------------------------------
# INSLIB is AGPL-3.0. Voltino TriSense is MIT. That is why this script fetches
# INSLIB at build time instead of the repository carrying a copy: linking the
# two produces a combined work covered by the AGPL, with all the obligations
# that implies (source offer, including over a network interface). If that does
# not suit your product, talk to INSLIB's author about a commercial licence, or
# use examples/GPS_INS_Localization, which is MIT all the way down.
# KFCore (the Kalman backend) is BSD-3-Clause.
#
# ---------------------------------------------------------------------------
# WHY THE WRAPPERS
# ---------------------------------------------------------------------------
# INSLIB and KFCore size their working arrays from -D flags, and the two that
# matter most (INS_UNKNOWNS_MAX, KALMAN_MAX_STATE_SIZE) decide how much STACK
# one filter call needs - the difference between 6.8 KB and 8.6 KB on a core
# that has 8 KB. The Arduino build offers no way to pass -D to a sketch, and
# arduino-pico does not support build_opt.h either.
#
# So the INSLIB sources land in ./inslib, which Arduino copies but does NOT
# compile (only the sketch root and ./src are compiled). Each one is then
# pulled into its own one-line translation unit under ./src that #includes
# src/inslib_config.h first. That is exactly what -D would have done, without
# patching a single line of INSLIB.
#
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DEST="$HERE/inslib"
WRAPDIR="$HERE/src"

INSLIB_URL=${INSLIB_URL:-https://github.com/jnz/INSLIB.git}
INSLIB_REF=${INSLIB_REF:-main}
KFCORE_URL=${KFCORE_URL:-https://github.com/jnz/KFCore.git}
KFCORE_REF=${KFCORE_REF:-main}

command -v git >/dev/null 2>&1 || { echo "fetch_inslib: git is required" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

# KFCore comes in as INSLIB's own submodule, so it lands at the revision that
# INSLIB was tested against rather than whatever KFCore's default branch happens
# to be today. That matters most when INSLIB_REF pins a release.
echo "fetch_inslib: cloning INSLIB ($INSLIB_REF) with KFCore"
git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$INSLIB_REF" \
          --recurse-submodules --shallow-submodules "$INSLIB_URL" "$TMP/INSLIB"

KFCORE_DIR="$TMP/INSLIB/KFCore"
if [ ! -f "$KFCORE_DIR/c/kalman_udu.c" ]; then
  # Some export paths ship INSLIB without the submodule wired up. Fall back to
  # cloning KFCore directly; pin KFCORE_REF yourself if you pinned INSLIB_REF.
  echo "fetch_inslib: submodule missing, cloning KFCore ($KFCORE_REF) separately"
  git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$KFCORE_REF" "$KFCORE_URL" "$TMP/KFCore"
  KFCORE_DIR="$TMP/KFCore"
fi

# Flatten both source trees into one directory. Every #include in INSLIB and
# KFCore is a quoted, unqualified name ("ins.h", "kalman_udu.h", ...), so once
# the files sit side by side each one resolves relative to its own includer -
# no -I path is needed, which is just as well, because a sketch cannot add one.
rm -rf "$DEST"
mkdir -p "$DEST"
cp "$TMP/INSLIB/src/"*.c "$TMP/INSLIB/src/"*.h "$DEST/"
cp "$KFCORE_DIR/c/"*.c   "$KFCORE_DIR/c/"*.h   "$DEST/"
cp "$TMP/INSLIB/LICENSE" "$DEST/LICENSE.INSLIB"
cp "$KFCORE_DIR/LICENSE" "$DEST/LICENSE.KFCore"

# Record what was fetched, so a bug report can name a version.
{
  printf 'INSLIB %s %s\n' "$INSLIB_REF" "$(git -C "$TMP/INSLIB" rev-parse HEAD)"
  printf 'KFCore %s\n' "$(git -C "$KFCORE_DIR" rev-parse HEAD)"
} > "$DEST/VERSIONS.txt"

# One wrapper per translation unit. Separate units, not a single unity build:
# INSLIB's files define same-named static helpers (time_diff_sec, qsquare, ...)
# that would collide if they were concatenated.
rm -f "$WRAPDIR"/inslib_tu_*.c
for src in "$DEST"/*.c; do
  base=$(basename "$src" .c)
  cat > "$WRAPDIR/inslib_tu_$base.c" <<EOF
/* Generated by fetch_inslib.sh - do not edit, your changes will be lost.
 *
 * Compiles inslib/$base.c with this example's build configuration. Edit
 * src/inslib_config.h to change it.
 */
#include "inslib_config.h"
#include "../inslib/$base.c"
EOF
done

n=$(ls "$WRAPDIR"/inslib_tu_*.c | wc -l | tr -d ' ')
echo "fetch_inslib: $DEST populated, $n translation-unit wrappers written"
echo "fetch_inslib: INSLIB is AGPL-3.0 - see the licensing note at the top of this script"
